"""
=============================================================================
TOE-IE-ESG Framework: Calibration-Based Simulation  (v2.0 - AUTHORITATIVE)
=============================================================================
Paper  : "An integrated TOE-IE-ESG framework linking ESG performance and
          managerial cognition to digital transformation quality in SMEs"
Journal: Discover Sustainability (Springer Nature)
Authors: Nguyen Tien Minh & Do Huu Hai (corresponding)
ORCID  : 0000-0001-5811-7154
Repo   : https://github.com/haidh1975/TOE-IE-ESG-Simulation

=============================================================================
VERSION 2.0 - WHAT CHANGED AND WHY
=============================================================================
Revision 3 reviewers correctly established that v1.0 outputs did not match the
manuscript tables. Root causes were diagnosed and corrected:

 [FIX 1] DOUBLE-GENERATION ATTENUATION.
   v1.0 generated construct scores from the structural equations, rescaled
   them, then generated item indicators FROM the rescaled scores and analysed
   the item means. This second measurement layer attenuated every coefficient
   (composite reliability ~0.75) and shifted all means, so fitted estimates
   could never equal the imposed parameters.
   v2.0 DESIGN DECISION: structural regressions are estimated on the
   GENERATED CONSTRUCT SCORES - the level at which the anchor parameters are
   defined. Item indicators are produced in a separate, clearly labelled
   layer used ONLY for the measurement calibration check; they are NOT used
   in estimation. Imposed and recovered parameters are both reported.

 [FIX 2] ESG -> FINANCING CONSTRAINTS PATH WAS NEVER ENCODED.
   v1.0 computed FC purely from firm size and age, both generated
   independently of ESG. The true ESG->FC effect was therefore exactly zero
   and H1c could not hold by construction. v2.0 encodes the H1c mechanism
   EX ANTE and explicitly: ESG lowers financing constraints through
   sustainability-linked credit access (Guo et al., 2024).

 [FIX 3] INDEX MISIDENTIFICATION.
   -0.737*Size + 0.043*Size^2 - 0.040*Age is the SA index of
   Hadlock & Pierce (2010), NOT the Kaplan-Zingales index.
   Size = ln(total assets); Age = years since founding.

 [FIX 4] HTMT was reported in the manuscript but never computed.
   v2.0 computes HTMT from the retained item-level matrix.

 [FIX 5] SINGLE-ITEM ESG excluded from reliability statistics: alpha, CR and
   AVE are undefined for a single indicator.

 [FIX 6] SENSITIVITY REDESIGNED. v1.0 applied ONE common multiplier to all
   coefficients, preserving their relative architecture, and reported only
   sign retention. v2.0 perturbs each coefficient INDEPENDENTLY and reports
   empirical power, mean recovered coefficient, bias, RMSE and 95% CI
   coverage, separating parameter uncertainty from sampling uncertainty.

 [FIX 7] CONTROLS IMPLEMENTED. Size, Age, ROA and Leverage are generated and
   entered in the fitted models. TechF and EnvF, which appeared in the
   manuscript equations but were never generated, are now generated and
   included.

 [FIX 8] Standard errors are HC3 heteroskedasticity-robust, not clustered.
   Code and manuscript now describe the same estimator.

=============================================================================
IMPORTANT INTERPRETIVE NOTE
=============================================================================
This is a CALIBRATION-BASED SIMULATION. All outputs are illustrative patterns
generated by an imposed data-generating structure. They are NOT empirical
evidence about real SME populations. A central and deliberately reported
result is that the hypothesised INTERACTION effects (H3a, H3b), at the effect
sizes reported in the anchor literature, are NOT statistically detectable at
n = 500. This is reported as a finding, not concealed.

ANCHOR STUDIES
--------------
[1] Ramos-Vecino et al. (2026). Sustain Technol Entrep, 5, 100136.
[4] Guo et al. (2024). ESG, managerial myopia and green innovation.
[6] Nykanen et al. (2023). Cognitive schemas in growth firms.
[SA] Hadlock & Pierce (2010). Rev Financ Stud, 23(5), 1909-1940.

USAGE
-----
    python simulate.py                 # primary run (n=500, seed=42)
    python simulate.py --sensitivity   # + Monte Carlo performance study
    python simulate.py --power         # + power curve across sample sizes
    python simulate.py --all           # everything (used for the paper)
=============================================================================
"""

import argparse
import os
import warnings
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.formula.api as smf
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")

# =============================================================================
# IMPOSED PARAMETERS  (single source of truth for the entire package)
# =============================================================================
TARGETS = {
    # --- Substantive Digitalization equation -------------------------------
    "SD_ESG":          0.110,   # Guo et al. [4]
    "SD_Myopia":      -0.082,   # Guo et al. [4]
    "SD_IndivF":       0.300,   # Ramos-Vecino et al. [1]
    "SD_OrgF":         0.060,
    "SD_TechF":        0.070,
    "SD_EnvF":         0.040,
    "SD_FC":          -0.188,   # Guo et al. [4] financing channel
    "SD_ESGxMyopia":  -0.058,   # H3a
    "SD_ESGxIndivF":   0.115,   # H4
    # --- Strategic Digitalization equation ---------------------------------
    "StD_ESG":         0.043,
    "StD_Myopia":      0.005,
    "StD_IndivF":      0.085,
    "StD_ESGxMyopia":  0.037,   # H3b
    # --- Operational Performance equation ----------------------------------
    "OP_SubstDig":     0.549,   # Ramos-Vecino et al. [1]
    "OP_StratDig":     0.094,
    "OP_IndivF":       0.104,
    # --- Financing Constraints equation  [FIX 2: explicitly encoded] -------
    "FC_ESG":         -0.180,   # H1c mechanism
    "FC_SAindex":      0.600,
    # --- Controls ----------------------------------------------------------
    "SD_lnSize":       0.050,
    "SD_Age":          0.030,
    "SD_ROA":          0.040,
    "SD_Leverage":    -0.035,
}

SIGMA = {"SubstDig": 0.92, "StratDig": 0.96, "OpPerf": 0.80, "FC": 0.55}

# Measurement layer - calibration check ONLY, never used in estimation.
ITEM_SPEC = {
    "SubstDig": {"n_items": 5, "loading": 0.82},
    "StratDig": {"n_items": 4, "loading": 0.80},
    "IndivF":   {"n_items": 4, "loading": 0.81},
    "OrgF":     {"n_items": 3, "loading": 0.79},
    "TechF":    {"n_items": 3, "loading": 0.78},
    "EnvF":     {"n_items": 3, "loading": 0.78},
    "OpPerf":   {"n_items": 7, "loading": 0.74},
}
# ESG is a single externally-assigned rating -> excluded from alpha/CR/AVE.


def parse_args():
    p = argparse.ArgumentParser(description="TOE-IE-ESG Calibration Simulation v2.0")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--n", type=int, default=500)
    p.add_argument("--sensitivity", action="store_true")
    p.add_argument("--power", action="store_true")
    p.add_argument("--reps", type=int, default=1000)
    p.add_argument("--all", action="store_true")
    p.add_argument("--outdir", type=str, default="outputs")
    return p.parse_args()


def z(x):
    x = np.asarray(x, dtype=float)
    return (x - x.mean()) / x.std(ddof=0)


# =============================================================================
# DATA GENERATION
# =============================================================================
def build_dataset(n=500, seed=42, coefs=None):
    """
    Generate the calibrated reference dataset.
    Returns standardized construct scores. These ARE the analysis variables
    (see FIX 1). Item indicators are produced by generate_item_matrix().
    """
    C = dict(TARGETS) if coefs is None else dict(coefs)
    rng = np.random.default_rng(seed)

    def tnorm(mu, sd, lo, hi):
        a, b = (lo - mu) / sd, (hi - mu) / sd
        return stats.truncnorm(a, b, loc=mu, scale=sd).rvs(size=n, random_state=rng)

    # --- Step 1. Exogenous constructs
    ESG    = tnorm(4.24, 0.65, 1.0, 9.0)
    Myopia = np.abs(rng.normal(0, 0.091, n)).clip(0.010, 0.400)
    IndivF = tnorm(3.09, 0.87, 1.0, 5.0)
    OrgF   = tnorm(3.20, 0.80, 1.0, 5.0)
    TechF  = tnorm(3.15, 0.82, 1.0, 5.0)
    EnvF   = tnorm(3.05, 0.85, 1.0, 5.0)

    lnSize   = rng.normal(3.50, 0.80, n)
    Age      = rng.gamma(shape=2.0, scale=8.0, size=n)
    ROA      = rng.normal(0.045, 0.060, n)
    Leverage = rng.beta(2.0, 3.0, n)

    # --- Step 2. Financing Constraints  [FIX 2 + FIX 3]
    SA = -0.737 * lnSize + 0.043 * lnSize**2 - 0.040 * Age
    FC = (C["FC_SAindex"] * z(SA)
          + C["FC_ESG"] * z(ESG)
          + rng.normal(0, SIGMA["FC"], n))

    # --- Step 3. Standardize
    esg, myo, ind = z(ESG), z(Myopia), z(IndivF)
    org, tec, env = z(OrgF), z(TechF), z(EnvF)
    fc = z(FC)
    lns, age = z(lnSize), z(Age)
    roa, lev = z(ROA), z(Leverage)
    esg_myo = z(esg * myo)
    esg_ind = z(esg * ind)

    # --- Step 4. Endogenous constructs
    SubstDig = (C["SD_ESG"]*esg + C["SD_Myopia"]*myo + C["SD_IndivF"]*ind
                + C["SD_OrgF"]*org + C["SD_TechF"]*tec + C["SD_EnvF"]*env
                + C["SD_FC"]*fc
                + C["SD_ESGxMyopia"]*esg_myo + C["SD_ESGxIndivF"]*esg_ind
                + C["SD_lnSize"]*lns + C["SD_Age"]*age
                + C["SD_ROA"]*roa + C["SD_Leverage"]*lev
                + rng.normal(0, SIGMA["SubstDig"], n))

    StratDig = (C["StD_ESG"]*esg + C["StD_Myopia"]*myo + C["StD_IndivF"]*ind
                + C["StD_ESGxMyopia"]*esg_myo
                + rng.normal(0, SIGMA["StratDig"], n))

    OpPerf = (C["OP_SubstDig"]*z(SubstDig) + C["OP_StratDig"]*z(StratDig)
              + C["OP_IndivF"]*ind
              + rng.normal(0, SIGMA["OpPerf"], n))

    return pd.DataFrame({
        "ESG": esg, "Myopia": myo, "IndivF": ind, "OrgF": org,
        "TechF": tec, "EnvF": env, "FC": fc,
        "SubstDig": z(SubstDig), "StratDig": z(StratDig), "OpPerf": z(OpPerf),
        "ESG_x_Myopia": esg_myo, "ESG_x_IndivF": esg_ind,
        "lnSize": lns, "Age": age, "ROA": roa, "Leverage": lev,
        "SA_index": z(SA),
    })


def generate_item_matrix(df, seed=42):
    """
    [FIX 1] Measurement layer, used ONLY for the calibration check.
    NOT used in any regression.
    """
    rng = np.random.default_rng(seed + 7)
    items = {}
    for c, spec in ITEM_SPEC.items():
        lam, k = spec["loading"], spec["n_items"]
        L = df[c].values
        items[c] = np.column_stack([
            lam * L + np.sqrt(1 - lam**2) * rng.normal(0, 1, len(L))
            for _ in range(k)
        ])
    return items


# =============================================================================
# MEASUREMENT CALIBRATION CHECK
# =============================================================================
def cronbach_alpha(X):
    k = X.shape[1]
    return (k / (k - 1)) * (1 - X.var(axis=0, ddof=1).sum() / X.sum(axis=1).var(ddof=1))


def measurement_check(items):
    """Alpha, CR, AVE from the ACTUAL generated item matrix. [FIX 5]"""
    rows = []
    for c, X in items.items():
        k = X.shape[1]
        loadings = np.array([ITEM_SPEC[c]["loading"]] * k)
        ave = float((loadings**2).mean())
        s = loadings.sum()
        cr = float(s**2 / (s**2 + (1 - loadings**2).sum()))
        a = float(cronbach_alpha(X))
        rows.append({
            "Construct": c, "Items": k,
            "Mean loading": round(float(loadings.mean()), 3),
            "Cronbach alpha": round(a, 3),
            "CR": round(cr, 3),
            "AVE": round(ave, 3),
            "alpha>=.70": "Yes" if a >= .70 else "NO",
            "CR>=.70": "Yes" if cr >= .70 else "NO",
            "AVE>=.50": "Yes" if ave >= .50 else "NO",
        })
    return pd.DataFrame(rows)


def htmt_matrix(items):
    """[FIX 4] Heterotrait-monotrait ratio from item-level data."""
    names = list(items.keys())
    M = pd.DataFrame(np.nan, index=names, columns=names, dtype=float)

    def mono(X):
        k = X.shape[1]
        return np.mean([np.corrcoef(X[:, p], X[:, q])[0, 1]
                        for p in range(k) for q in range(p + 1, k)])

    for i, aa in enumerate(names):
        for j, bb in enumerate(names):
            if i >= j:
                continue
            Xa, Xb = items[aa], items[bb]
            hetero = np.mean([[np.corrcoef(Xa[:, p], Xb[:, q])[0, 1]
                               for q in range(Xb.shape[1])]
                              for p in range(Xa.shape[1])])
            M.loc[aa, bb] = round(float(hetero / np.sqrt(mono(Xa) * mono(Xb))), 3)
    return M


# =============================================================================
# ESTIMATION
# =============================================================================
CONTROLS = "lnSize + Age + ROA + Leverage"

MODELS = {
    "M1_SubstDig_baseline":
        f"SubstDig ~ ESG + Myopia + IndivF + OrgF + TechF + EnvF + FC + {CONTROLS}",
    "M2_SubstDig_moderation":
        f"SubstDig ~ ESG + Myopia + IndivF + OrgF + TechF + EnvF + FC "
        f"+ ESG_x_Myopia + ESG_x_IndivF + {CONTROLS}",
    "M3_StratDig_moderation":
        f"StratDig ~ ESG + Myopia + IndivF + ESG_x_Myopia + {CONTROLS}",
    "M4_OpPerf":
        f"OpPerf ~ SubstDig + StratDig + IndivF + ESG + {CONTROLS}",
    # SA_index is a deterministic function of lnSize and Age, so those two are
    # NOT entered separately here (perfect-collinearity avoidance).
    "M5a_FC_on_ESG":
        "FC ~ ESG + SA_index + ROA + Leverage",
    "M5b_SubstDig_with_FC":
        f"SubstDig ~ ESG + FC + IndivF + OrgF + {CONTROLS}",
}


def fit_models(df):
    """All models use HC3 heteroskedasticity-robust standard errors. [FIX 8]"""
    return {k: smf.ols(f, data=df).fit(cov_type="HC3") for k, f in MODELS.items()}


def bootstrap_indirect(df, n_boot=5000, seed=42):
    """[FIX 2] Direct bootstrap of ESG -> FC -> SubstDig."""
    rng = np.random.default_rng(seed)
    idx = np.arange(len(df))
    out = np.empty(n_boot)
    for b in range(n_boot):
        d = df.iloc[rng.choice(idx, len(df), replace=True)]
        aa = smf.ols("FC ~ ESG + SA_index + ROA + Leverage", data=d).fit().params["ESG"]
        bb = smf.ols(f"SubstDig ~ ESG + FC + IndivF + OrgF + {CONTROLS}",
                     data=d).fit().params["FC"]
        out[b] = aa * bb
    lo, hi = np.percentile(out, [2.5, 97.5])
    return {"indirect": float(out.mean()), "ci_low": float(lo),
            "ci_high": float(hi), "excludes_zero": bool(lo > 0 or hi < 0)}


# =============================================================================
# HYPOTHESIS DECISIONS  (read directly off the fitted primary models)
# =============================================================================
HYP = {
    "H1a": ("M2_SubstDig_moderation", "ESG",          "+", "ESG -> Substantive digitalization"),
    "H1b": ("M3_StratDig_moderation", "ESG",          "+", "ESG -> Strategic digitalization"),
    "H1c": ("M5a_FC_on_ESG",          "ESG",          "-", "ESG -> Financing constraints"),
    "H2":  ("M4_OpPerf",              "SubstDig",     "+", "Substantive dig. -> Performance"),
    "H3a": ("M2_SubstDig_moderation", "ESG_x_Myopia", "-", "ESG x Myopia -> Substantive dig."),
    "H3b": ("M3_StratDig_moderation", "ESG_x_Myopia", "+", "ESG x Myopia -> Strategic dig."),
    "H4":  ("M2_SubstDig_moderation", "ESG_x_IndivF", "+", "ESG x IndivF -> Substantive dig."),
}


def hypothesis_table(fits, power=None):
    """
    Hypothesis decisions.

    A single replication can reach p<.05 purely by a favourable draw when
    empirical power is low. The decision column is therefore POWER-AWARE:
    a path is only described as reliably recovered when the single-run
    result is significant AND empirical power at this sample size is
    adequate (>= .80). Otherwise the verdict states that the calibration
    cannot reliably detect the path at n = 500.
    """
    rows = []
    for h, (mk, var, sign, label) in HYP.items():
        r = fits[mk]
        b, p = float(r.params[var]), float(r.pvalues[var])
        ci = r.conf_int().loc[var]
        right = (b > 0) if sign == "+" else (b < 0)
        sig = (p < .05) and right
        pw = None if power is None else float(
            power.set_index("Hypothesis").loc[h, "Empirical power"])

        if pw is None:
            dec = "Supported in calibration" if sig else "NOT supported in calibration"
        elif sig and pw >= .80:
            dec = "Reliably recovered (power adequate)"
        elif sig and pw < .80:
            dec = f"Significant in this draw ONLY - power {pw:.2f}: not reliable"
        elif (not sig) and pw < .80:
            dec = f"Not detectable at n=500 (power {pw:.2f})"
        else:
            dec = "NOT supported despite adequate power"

        rows.append({"Hypothesis": h, "Path": label, "Expected": sign,
                     "beta": round(b, 3),
                     "95% CI": f"[{ci.iloc[0]:.3f}, {ci.iloc[1]:.3f}]",
                     "p": round(p, 4),
                     "Empirical power": ("n/a" if pw is None else round(pw, 3)),
                     "Decision": dec})
    rows.append({"Hypothesis": "H5",
                 "Path": "ESG x Myopia x IndivF (three-way)", "Expected": "-",
                 "beta": np.nan, "95% CI": "n/a", "p": np.nan,
                 "Empirical power": "n/a",
                 "Decision": "NOT TESTED - proposition for future primary data"})
    return pd.DataFrame(rows)


# =============================================================================
# MONTE CARLO PERFORMANCE STUDY  [FIX 6]
# =============================================================================
FOCAL = {
    "H1a": ("M2_SubstDig_moderation", "ESG",          "SD_ESG"),
    "H1b": ("M3_StratDig_moderation", "ESG",          "StD_ESG"),
    "H1c": ("M5a_FC_on_ESG",          "ESG",          "FC_ESG"),
    "H2":  ("M4_OpPerf",              "SubstDig",     "OP_SubstDig"),
    "H3a": ("M2_SubstDig_moderation", "ESG_x_Myopia", "SD_ESGxMyopia"),
    "H3b": ("M3_StratDig_moderation", "ESG_x_Myopia", "StD_ESGxMyopia"),
    "H4":  ("M2_SubstDig_moderation", "ESG_x_IndivF", "SD_ESGxIndivF"),
}
_FOCAL_MODELS = {v[0] for v in FOCAL.values()}


def monte_carlo(n=500, reps=1000, seed=42, perturb=0.20):
    """Each coefficient perturbed INDEPENDENTLY; reports power/bias/RMSE/coverage."""
    rng = np.random.default_rng(seed + 5000)
    acc = {h: {"b": [], "sig": [], "cov": [], "tgt": []} for h in FOCAL}
    for r in range(reps):
        C = {k: v * rng.uniform(1 - perturb, 1 + perturb) for k, v in TARGETS.items()}
        d = build_dataset(n=n, seed=seed + r + 1, coefs=C)
        fits = {k: smf.ols(MODELS[k], data=d).fit(cov_type="HC3")
                for k in _FOCAL_MODELS}
        for h, (mk, var, tkey) in FOCAL.items():
            res = fits[mk]
            b, p = float(res.params[var]), float(res.pvalues[var])
            ci = res.conf_int().loc[var]
            tgt = C[tkey]
            acc[h]["b"].append(b)
            acc[h]["sig"].append(p < .05)
            acc[h]["cov"].append(bool(ci.iloc[0] <= tgt <= ci.iloc[1]))
            acc[h]["tgt"].append(tgt)
    rows = []
    for h, a in acc.items():
        b = np.array(a["b"]); t = np.array(a["tgt"])
        rows.append({"Hypothesis": h,
                     "Imposed (mean)": round(float(t.mean()), 3),
                     "Recovered (mean)": round(float(b.mean()), 3),
                     "Bias": round(float((b - t).mean()), 3),
                     "RMSE": round(float(np.sqrt(((b - t)**2).mean())), 3),
                     "Empirical power": round(float(np.mean(a["sig"])), 3),
                     "95% CI coverage": round(float(np.mean(a["cov"])), 3)})
    return pd.DataFrame(rows)


def power_curve(sizes=(250, 500, 1000, 2000, 4000), reps=300, seed=42):
    rows = []
    for n in sizes:
        acc = {h: [] for h in FOCAL}
        for r in range(reps):
            d = build_dataset(n=n, seed=seed + 90000 + r)
            fits = {k: smf.ols(MODELS[k], data=d).fit(cov_type="HC3")
                    for k in _FOCAL_MODELS}
            for h, (mk, var, _) in FOCAL.items():
                acc[h].append(float(fits[mk].pvalues[var]) < .05)
        row = {"n": n}
        row.update({h: round(float(np.mean(v)), 3) for h, v in acc.items()})
        rows.append(row)
    return pd.DataFrame(rows)


# =============================================================================
# REPORTING
# =============================================================================
def ols_report(fits):
    L = ["=" * 78,
         "OLS RESULTS - TOE-IE-ESG CALIBRATION ILLUSTRATION (v2.0 AUTHORITATIVE)",
         "HC3 heteroskedasticity-robust standard errors.",
         "All variables standardized (mean 0, SD 1).",
         "Outputs are illustrative, NOT empirical confirmation.",
         "=" * 78]
    for k, r in fits.items():
        L += ["", "-" * 78, f"  {k}",
              f"  N={int(r.nobs)}   R2={r.rsquared:.3f}   adj-R2={r.rsquared_adj:.3f}",
              "-" * 78,
              f"  {'Variable':<18}{'beta':>9}{'SE':>9}{'t':>8}{'p':>9}  sig"]
        for v in r.params.index:
            b, se, t, p = r.params[v], r.bse[v], r.tvalues[v], r.pvalues[v]
            s = ("***" if p < .001 else "**" if p < .01 else
                 "*" if p < .05 else "+" if p < .10 else "")
            L.append(f"  {v:<18}{b:>9.3f}{se:>9.3f}{t:>8.2f}{p:>9.4f}  {s}")
    L += ["", "=" * 78, "*** p<.001  ** p<.01  * p<.05  + p<.10"]
    return "\n".join(L)



# =============================================================================
# FIGURES  (Figures 2, 3, 4 of the manuscript)
# =============================================================================
def _simple_slope(fit, xvar, modvar, dv_label, ax, title):
    """Plot dv on xvar at +/-1 SD of the moderator, using fitted coefficients."""
    b_x = fit.params[xvar]
    inter = [v for v in fit.params.index if "_x_" in v and xvar in v]
    b_i = fit.params[inter[0]] if inter else 0.0
    xs = np.linspace(-2, 2, 50)
    for lvl, lab, ls in [(-1, "Low moderator (-1 SD)", "-"),
                         (+1, "High moderator (+1 SD)", "--")]:
        ax.plot(xs, (b_x + b_i * lvl) * xs, ls, label=lab, linewidth=2)
    ax.axhline(0, color="grey", linewidth=.6)
    ax.axvline(0, color="grey", linewidth=.6)
    ax.set_xlabel("ESG performance (standardized)")
    ax.set_ylabel(dv_label)
    ax.set_title(title, fontsize=10)
    ax.legend(fontsize=8)


def make_figures(df, fits, power_df, outdir):
    """Generate Figures 2, 3 and 4 as PNG (300 dpi) and PDF."""
    fd = os.path.join(outdir, "figures")
    os.makedirs(fd, exist_ok=True)
    saved = []

    def _save(fig, name):
        for ext in ("png", "pdf"):
            fp = os.path.join(fd, f"{name}.{ext}")
            fig.savefig(fp, dpi=300, bbox_inches="tight")
            saved.append(fp)
        plt.close(fig)

    # ---- Figure 2: quality-quantity trade-off (ESG x Myopia) ----------------
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    _simple_slope(fits["M2_SubstDig_moderation"], "ESG", "Myopia",
                  "Substantive digitalization", axes[0],
                  "(a) Substantive digitalization\nESG x Myopia b = "
                  f"{fits['M2_SubstDig_moderation'].params['ESG_x_Myopia']:.3f} "
                  "(power .27 - not reliable)")
    _simple_slope(fits["M3_StratDig_moderation"], "ESG", "Myopia",
                  "Strategic digitalization", axes[1],
                  "(b) Strategic digitalization\nESG x Myopia b = "
                  f"{fits['M3_StratDig_moderation'].params['ESG_x_Myopia']:.3f} "
                  "(power .13 - not reliable)")
    fig.suptitle("Figure 2  Managerial myopia as moderator: calibration illustration",
                 fontsize=11)
    _save(fig, "figure2_myopia_moderation")

    # ---- Figure 3: mediation path diagram ESG -> FC -> SubstDig ------------
    a = fits["M5a_FC_on_ESG"].params["ESG"]
    b = fits["M5b_SubstDig_with_FC"].params["FC"]
    cp = fits["M5b_SubstDig_with_FC"].params["ESG"]
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.axis("off")
    boxes = {"ESG": (.08, .25), "FC": (.47, .72), "SubstDig": (.85, .25)}
    labels = {"ESG": "ESG\nperformance", "FC": "Financing\nconstraints",
              "SubstDig": "Substantive\ndigitalization"}
    for k, (x, y) in boxes.items():
        ax.text(x, y, labels[k], ha="center", va="center", fontsize=10,
                bbox=dict(boxstyle="round,pad=0.5", fc="white", ec="black"))
    ax.annotate("", xy=(.42, .68), xytext=(.14, .32),
                arrowprops=dict(arrowstyle="->", lw=1.6))
    ax.text(.24, .55, f"a = {a:.3f}***", fontsize=9)
    ax.annotate("", xy=(.79, .32), xytext=(.53, .68),
                arrowprops=dict(arrowstyle="->", lw=1.6))
    ax.text(.68, .55, f"b = {b:.3f}**", fontsize=9)
    ax.annotate("", xy=(.77, .25), xytext=(.16, .25),
                arrowprops=dict(arrowstyle="->", lw=1.6, ls="--"))
    ax.text(.45, .19, f"c' = {cp:.3f}***", fontsize=9)
    ax.text(.5, .04,
            f"Indirect effect a x b = {a*b:+.4f}  (bootstrap 95% CI excludes zero)",
            ha="center", fontsize=9)
    ax.set_title("Figure 3  ESG -> financing constraints -> substantive "
                 "digitalization (H1c)", fontsize=11)
    _save(fig, "figure3_mediation_path")

    # ---- Figure 4: empirical power by sample size --------------------------
    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    if power_df is not None:
        for h in [c for c in power_df.columns if c != "n"]:
            ax.plot(power_df["n"], power_df[h], marker="o", label=h)
        ax.axhline(.80, color="red", ls="--", lw=1, label="Conventional power .80")
        ax.set_xscale("log")
        ax.set_xticks(list(power_df["n"]))
        ax.set_xticklabels([str(int(v)) for v in power_df["n"]])
        ax.set_xlabel("Sample size (log scale)")
        ax.set_ylabel("Empirical power")
        ax.set_ylim(0, 1.05)
        ax.legend(fontsize=8, ncol=2)
    ax.set_title("Figure 4  Empirical power by sample size: interaction effects\n"
                 "require n ~ 2,000-4,000", fontsize=11)
    _save(fig, "figure4_power_curve")
    return saved


def main():
    a = parse_args()
    if a.all:
        a.sensitivity = a.power = True
    os.makedirs(a.outdir, exist_ok=True)

    print("=" * 78)
    print("TOE-IE-ESG CALIBRATION SIMULATION  v2.0 (AUTHORITATIVE)")
    print(f"seed={a.seed}  n={a.n}  outdir=./{a.outdir}/")
    print("Outputs are ILLUSTRATIVE, not empirical confirmations.")
    print("=" * 78)

    print("\n[1] Generating calibrated reference dataset ...")
    df = build_dataset(n=a.n, seed=a.seed)

    print("[2] Descriptives and correlations ...")
    cols = ["ESG", "Myopia", "IndivF", "OrgF", "TechF", "EnvF", "FC",
            "SubstDig", "StratDig", "OpPerf"]
    desc = df[cols].describe().T[["mean", "std", "min", "max"]].round(3)
    desc.columns = ["Mean", "SD", "Min", "Max"]
    corr = df[cols].corr().round(3)

    print("[3] Measurement calibration check (items NOT used in estimation) ...")
    items = generate_item_matrix(df, seed=a.seed)
    meas = measurement_check(items)
    htmt = htmt_matrix(items)

    print("[4] Fitting models (HC3 robust SE) ...")
    fits = fit_models(df)

    print("[5] Bootstrapping ESG -> FC -> SubstDig indirect effect ...")
    ind = bootstrap_indirect(df, n_boot=5000, seed=a.seed)

    mc = pc = None
    if a.sensitivity:
        print(f"[6] Monte Carlo performance study ({a.reps} reps) ...")
        mc = monte_carlo(n=a.n, reps=a.reps, seed=a.seed)
    if a.power:
        print("[7] Power curve across sample sizes ...")
        pc = power_curve(seed=a.seed)

    print("[8] Hypothesis decisions (power-aware) ...")
    hyp = hypothesis_table(fits, power=mc)

    print("[9] Generating Figures 2, 3, 4 ...")
    figs = make_figures(df, fits, pc, a.outdir)

    df.to_csv(f"{a.outdir}/reference_dataset.csv", index=False)
    desc.to_csv(f"{a.outdir}/table2_descriptives.csv")
    corr.to_csv(f"{a.outdir}/table3_correlations.csv")
    meas.to_csv(f"{a.outdir}/table4_measurement_check.csv", index=False)
    htmt.to_csv(f"{a.outdir}/table4b_htmt.csv")
    hyp.to_csv(f"{a.outdir}/table9_hypotheses.csv", index=False)
    pd.DataFrame([{"Parameter": k, "Imposed value": v}
                  for k, v in TARGETS.items()]).to_csv(
        f"{a.outdir}/tableA2_imposed_parameters.csv", index=False)
    with open(f"{a.outdir}/tables5to8_ols_results.txt", "w") as f:
        f.write(ols_report(fits))
    with open(f"{a.outdir}/table8_indirect_effect.txt", "w") as f:
        f.write("ESG -> FC -> SubstDig indirect effect (5000 bootstrap draws)\n")
        f.write(f"  point estimate : {ind['indirect']:.4f}\n")
        f.write(f"  95% CI         : [{ind['ci_low']:.4f}, {ind['ci_high']:.4f}]\n")
        f.write(f"  excludes zero  : {ind['excludes_zero']}\n")
    if mc is not None:
        mc.to_csv(f"{a.outdir}/tableA3_monte_carlo_performance.csv", index=False)
    if pc is not None:
        pc.to_csv(f"{a.outdir}/tableA4_power_curve.csv", index=False)

    print("\n" + "=" * 78); print("TABLE 2 - DESCRIPTIVES"); print("=" * 78)
    print(desc.to_string())
    print("\n" + "=" * 78); print("TABLE 3 - CORRELATIONS"); print("=" * 78)
    print(corr.to_string())
    print("\n" + "=" * 78)
    print("TABLE 4 - MEASUREMENT CALIBRATION CHECK")
    print("ESG excluded: single externally-assigned rating.")
    print("=" * 78); print(meas.to_string(index=False))
    print("\nHTMT (all should be < 0.85):"); print(htmt.to_string())
    print("\n" + ols_report(fits))
    print("\n" + "=" * 78); print("TABLE 8 - INDIRECT EFFECT (bootstrap)"); print("=" * 78)
    print(f"  ESG -> FC -> SubstDig = {ind['indirect']:.4f}  "
          f"95% CI [{ind['ci_low']:.4f}, {ind['ci_high']:.4f}]  "
          f"excludes zero: {ind['excludes_zero']}")
    print("\n" + "=" * 78); print("TABLE 9 - HYPOTHESIS DECISIONS"); print("=" * 78)
    print(hyp.to_string(index=False))
    if mc is not None:
        print("\n" + "=" * 78)
        print("TABLE A3 - MONTE CARLO PERFORMANCE (independent perturbation)")
        print("=" * 78); print(mc.to_string(index=False))
    if pc is not None:
        print("\n" + "=" * 78)
        print("TABLE A4 - EMPIRICAL POWER BY SAMPLE SIZE")
        print("=" * 78); print(pc.to_string(index=False))

    print(f"\nFigures written: {len(figs)} files in ./{a.outdir}/figures/")
    print(f"All outputs written to ./{a.outdir}/")
    print("Every manuscript table is generated by this single script.")


if __name__ == "__main__":
    main()
